Module7 task1
htmlacademy-ecmascript/1343543-cinemaddict-12 pull request #11
Opened 2020-09-08 12:19 UTC by dmitrykhalimov

С великим скрипом сделал :(

Из актуальных проблем:
- Не работают элементы управления попапов блоков экстра (не разобрался почему, но т.к. это доп. задание - пока оставил как есть).
- Если включен фильтр (например favorites), при открытии попапа и отжатии кнопки favorites попап не перерисовывается. В моем понимании, правда, это не баг а фича - т.к. элемент удаляется из списка и попап является непосредственной его частью и удаляется вместе с отбракованным элементом. Да и в ТЗ не оговорено.

2020-09-08 19:54 UTC, balesniy commented
> * Если включен фильтр (например favorites), при открытии попапа и отжатии кнопки favorites попап не перерисовывается. В моем понимании, правда, это не баг а фича - т.к. элемент удаляется из списка и попап является непосредственной его частью и удаляется вместе с отбракованным элементом. Да и в ТЗ не оговорено.

в принципе поведение логичное, но нужно поправить ошибку TypeError: undefined is not an object (evaluating 'this._filmPresenter[data.id].openFilmPopup') в _handleModelEvent - презентер удаляется при очистке доски, а update пробует вызвать у него openFilmPopup. можно добавить проверок.

2020-09-08 20:14 UTC, balesniy requested changes

2020-09-08 20:14 UTC, balesniy commented on src/presenter/board.js
> +        this._filmPresenter[data.id].openFilmPopup(); // если изменения сделаны из попапа после перерисовки открыть попап назад
вот тут падает ошибка при включенном фильтре, если мы удалили презентер, то попап не открыть

2020-09-08 20:14 UTC, balesniy commented on src/presenter/board.js
> +      this._renderFilm(this._extraRated.getElement().querySelector(`.films-list__container`), topRatedFilms[i], this._filmRatedPresenter);
работу с элементами лучше перенести в компонент, см https://up.htmlacademy.ru/ecmascript/12/criteries#d26

2020-09-08 20:14 UTC, balesniy commented on src/presenter/board.js
> +    } else {
тут можно использовать тернарный

2020-09-08 20:14 UTC, balesniy commented on src/utils/filter.js
> +export const makeFilters = {
повторяет countFilters ?

2020-09-08 20:14 UTC, balesniy commented on src/view/film-details.js
>            <div class="film-details__emoji-list">
тут просится цикл для генерации списка

2020-09-08 20:14 UTC, balesniy commented on src/view/film-details.js
> +    const commentId = evt.target.parentNode.parentNode.parentNode.getAttribute(`data-comment-id`);
посмотри на метод closest

2020-09-09 08:51 UTC, dmitrykhalimov commented on src/presenter/board.js
> +        this._filmPresenter[data.id].openFilmPopup(); // если изменения сделаны из попапа после перерисовки открыть попап назад
Спасибо! Принято! Исправлена ошибка.

2020-09-09 09:10 UTC, dmitrykhalimov commented on src/presenter/board.js
> +      this._renderFilm(this._extraRated.getElement().querySelector(`.films-list__container`), topRatedFilms[i], this._filmRatedPresenter);
Исправлено, добавлен новый метод getContainer()

2020-09-09 09:14 UTC, dmitrykhalimov commented on src/presenter/board.js
> +    } else {
Заменено на тернарный оператор.

2020-09-09 09:18 UTC, dmitrykhalimov commented on src/view/film-details.js
> +    const commentId = evt.target.parentNode.parentNode.parentNode.getAttribute(`data-comment-id`);
Крутая штука! Исправил :)

2020-09-09 09:36 UTC, dmitrykhalimov commented on src/view/film-details.js
>            <div class="film-details__emoji-list">
заменено на функцию генерации списка.

2020-09-09 10:40 UTC, dmitrykhalimov commented on src/utils/filter.js
> +export const makeFilters = {
Просто countFilters считает только количество, а мне нужны были конкретные результаты, и я поленился переписывать :( Исправлено: сделана универсальная функция фильтра.

2020-09-09 11:57 UTC, dmitrykhalimov commented on src/presenter/board.js
> +    // TODO: не работают интерактивные элементы попапа (!)
Спасибо!! Разобрался, исправлено.

2020-09-09 12:12 UTC, dmitrykhalimov commented
Очень странно, что сборка которую собрал Кексобот - старая :/

2020-09-10 13:33 UTC, balesniy approved these changes

2020-09-10 13:33 UTC, balesniy commented on src/view/film-details.js
> +    for (let emoji of EMOJIS) {
const

2020-09-10 13:33 UTC, balesniy commented on src/view/film-details.js
> +  _buttonDeleteClickHandler(evt) {
посмотри на https://up.htmlacademy.ru/ecmascript/12/criteries#d8 - обработчики "снизу"

2020-09-10 13:34 UTC, merged

2020-09-10 13:44 UTC, dmitrykhalimov commented on src/view/film-details.js
> +    for (let emoji of EMOJIS) {
Он тогда крашится :( Там же накопление

`    for (let emoji of EMOJIS) {
      result += `

2020-09-10 13:46 UTC, balesniy commented on src/view/film-details.js
> +    for (let emoji of EMOJIS) {
я про emoji, он не меняется в блоке

2020-09-10 14:17 UTC, dmitrykhalimov commented on src/view/film-details.js
> +  _buttonDeleteClickHandler(evt) {
Исправлено, методы классов приведены в соответствие с критерием Д8

2020-09-11 11:04 UTC, dmitrykhalimov commented on src/view/film-details.js
> +    for (let emoji of EMOJIS) {
Ой :( Исправлено.