Module9 task2
htmlacademy-ecmascript/1343543-cinemaddict-12 pull request #16
Opened 2020-09-15 12:44 UTC by dmitrykhalimov

Завершает работы по проекту.

- Исправлены предыдущие замечания
- Исправлены/добавлены функции:
1. В краткой карточке фильма, описание длиннее 140 символов отображается как 139 символов + ...
2. Если с сервера не приходят жанры - не отображать ничего (ранее отображалось Undefined). Из развернутой карточки поле Genre не удаляется.
3. По ТЗ - при изменении фильтров сбрасывается сортировка
4. При установке флагов фильма больше не "сворачивается" доска отображенных фильмов до 5 фильмов
5. В хэдере не меняется ранг при применении фильмов
6. Блоки Most Commented и Top Rated ведут себя в соответствии с ТЗ - если нет фильмов для отрисовки, не отображаются.
7. Исправлен баг, когда не удалялись eventListener (onClick)

? Иногда с сервера приходит вместо описания '.' - я не стал добавлять специальную проверку, в ТЗ - не указано:)
? Убирать ли комментарии из кода?

2020-09-15 19:38 UTC, balesniy commented
фильтры влияют на отображение экстра блоков, кейс такой - убираем все избранные, блоки экстра не отображаются при включенном фильтре, но если добавить хоть один в избранное, то все 4 фильма в блоках

2020-09-15 19:42 UTC, balesniy commented
добавление фильма в просмотренные не отображается в статистике за сегодня, но отмечается в all time

2020-09-15 19:49 UTC, balesniy commented on src/presenter/film.js
> +    document.removeEventListener(`keydown`, this._handleEscKeyDown);
слишком оптимистично) если падает ошибка, то окно уже с клавиатуры не закрыть

2020-09-15 19:52 UTC, balesniy commented on src/utils/common.js
> +export const randomString = (length) => {
функции нужен глагол в названии, переменная rnd не входит в согласованный список допустимых сокращений.

2020-09-15 19:55 UTC, dmitrykhalimov commented on src/utils/common.js
> +export const randomString = (length) => {
исправлено, я не так понял сначала :)

2020-09-15 20:52 UTC, dmitrykhalimov commented on src/presenter/film.js
> +    document.removeEventListener(`keydown`, this._handleEscKeyDown);
Исправлено :) В презентере создан отдельный метод removeEventListener, который вызывается из _handleModelEvent (когда общение с сервером уже или произошло успешно или до этого не дошло). Заодно слегка зарефакторил опрос всех трех список презентеров.

2020-09-15 21:11 UTC, dmitrykhalimov commented
> фильтры влияют на отображение экстра блоков, кейс такой - убираем все избранные, блоки экстра не отображаются при включенном фильтре, но если добавить хоть один в избранное, то все 4 фильма в блоках

Исправлено.

2020-09-15 21:36 UTC, dmitrykhalimov commented
> добавление фильма в просмотренные не отображается в статистике за сегодня, но отмечается в all time

Исправлено. Новое поведение: при нажатии на Watched, полю watchingDate присваивается текущее время. При отжатии null (null, потому что при первом запуске с сервера фильмы с isWatched false приходят именно с watchingDate === null). Любопытно, что при передаче на сервер watchingDate === null, сервер возвращает 1 1970 :) Но т.к. есть проверка на isWatched, то это не влияет на работу.

2020-09-16 15:44 UTC, balesniy requested changes

2020-09-16 15:44 UTC, balesniy commented on src/presenter/board.js
> +  OPEN: `handleFilmPopupOpen`,
интересное решение, но очень "хрупкое", похоже на нарушение критерия про инкапсуляцию. попробуй определить методы на дочернем компоненте и вызывать их явно

2020-09-16 15:44 UTC, balesniy commented on src/presenter/board.js
>        return;
сохранилась проблема с блоками экстра при активации "нулевого" фильтра - вот это return не дает им отрисоваться, придется немного поменять логику в методе

2020-09-16 18:00 UTC, dmitrykhalimov commented on src/presenter/board.js
> +  OPEN: `handleFilmPopupOpen`,
Исправлено, добавил явный вызов методов.

2020-09-16 18:00 UTC, dmitrykhalimov commented on src/presenter/board.js
>        return;
Исправлено.

2020-09-16 20:48 UTC, dmitrykhalimov commented
Обнаружил баг: добавляемые и удаляемые комментарии не сохранялись в localstorage (я забыл написать для них функции). Сейчас все работает как надо.

2020-09-16 20:54 UTC, balesniy commented
я вот еще одну особенность заметил - открытый попап из most commented закрывается при удалении комментария, логику такого поведения я понимаю, но выглядит странновато) чтобы поправить придется условия в контроллеры добавлять, но я бы так на проверку отправил, если попросят, время поправить есть.

2020-09-17 04:03 UTC, dmitrykhalimov commented
> я вот еще одну особенность заметил - открытый попап из most commented закрывается при удалении комментария, логику такого поведения я понимаю, но выглядит странновато) чтобы поправить придется условия в контроллеры добавлять, но я бы так на проверку отправил, если попросят, время поправить есть.

Ой :( Да, согласен. Надеюсь не попросят :)

2020-09-17 05:35 UTC, balesniy commented
тогда осталось собрать архив на проверку :100:

2020-09-17 05:35 UTC, merged